# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.style_check_response import StyleCheckResponse
from .raw_client import AsyncRawStyleChecksClient, RawStyleChecksClient


class StyleChecksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStyleChecksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStyleChecksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStyleChecksClient
        """
        return self._raw_client

    def create_style_check(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import acrolinx

        client = acrolinx()
        client.style_checks.create_style_check(
            document_id="document_id",
        )
        """
        _response = self._raw_client.create_style_check(document_id=document_id, request_options=request_options)
        return _response.data

    def get_style_check(
        self, workflow_id: str, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> StyleCheckResponse:
        """
        Parameters
        ----------
        workflow_id : str

        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StyleCheckResponse
            Successful Response

        Examples
        --------
        from acrolinx576596 import acrolinx

        client = acrolinx()
        client.style_checks.get_style_check(
            workflow_id="workflow_id",
            document_id="document_id",
        )
        """
        _response = self._raw_client.get_style_check(
            workflow_id, document_id=document_id, request_options=request_options
        )
        return _response.data


class AsyncStyleChecksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStyleChecksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStyleChecksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStyleChecksClient
        """
        return self._raw_client

    async def create_style_check(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx576596 import Asyncacrolinx

        client = Asyncacrolinx()


        async def main() -> None:
            await client.style_checks.create_style_check(
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_style_check(document_id=document_id, request_options=request_options)
        return _response.data

    async def get_style_check(
        self, workflow_id: str, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> StyleCheckResponse:
        """
        Parameters
        ----------
        workflow_id : str

        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StyleCheckResponse
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx576596 import Asyncacrolinx

        client = Asyncacrolinx()


        async def main() -> None:
            await client.style_checks.get_style_check(
                workflow_id="workflow_id",
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_style_check(
            workflow_id, document_id=document_id, request_options=request_options
        )
        return _response.data
