# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.dialects import Dialects
from ..types.tones import Tones
from ..types.workflow_response import WorkflowResponse
from .raw_client import AsyncRawStyleSuggestionsClient, RawStyleSuggestionsClient
from .types.style_suggestions_get_style_suggestion_response import StyleSuggestionsGetStyleSuggestionResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StyleSuggestionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStyleSuggestionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStyleSuggestionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStyleSuggestionsClient
        """
        return self._raw_client

    def create_style_suggestion(
        self,
        *,
        file_upload: core.File,
        dialect: typing.Optional[Dialects] = OMIT,
        tone: typing.Optional[Tones] = OMIT,
        style_guide: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Start a style and brand suggestion run. Returns a workflow ID for each file.

        Parameters
        ----------
        file_upload : core.File
            See core.File for more documentation

        dialect : typing.Optional[Dialects]
            The intended dialect of the text to edit.

        tone : typing.Optional[Tones]
            The intended tone of the text to edit.

        style_guide : typing.Optional[str]
            The style guide to use for the text to edit. Can be a style guide ID or the name of a generic style guide, e.g. 'ap', 'chicago', or 'microsoft'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Successful Response

        Examples
        --------
        from acrolinx import acrolinx

        client = acrolinx(
            api_key="YOUR_API_KEY",
        )
        client.style_suggestions.create_style_suggestion()
        """
        _response = self._raw_client.create_style_suggestion(
            file_upload=file_upload,
            dialect=dialect,
            tone=tone,
            style_guide=style_guide,
            request_options=request_options,
        )
        return _response.data

    def get_style_suggestion(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StyleSuggestionsGetStyleSuggestionResponse:
        """
        Get the results of a suggestion run.

        Parameters
        ----------
        workflow_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StyleSuggestionsGetStyleSuggestionResponse
            Successful Response

        Examples
        --------
        from acrolinx import acrolinx

        client = acrolinx(
            api_key="YOUR_API_KEY",
        )
        client.style_suggestions.get_style_suggestion(
            workflow_id="workflow_id",
        )
        """
        _response = self._raw_client.get_style_suggestion(workflow_id, request_options=request_options)
        return _response.data


class AsyncStyleSuggestionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStyleSuggestionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStyleSuggestionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStyleSuggestionsClient
        """
        return self._raw_client

    async def create_style_suggestion(
        self,
        *,
        file_upload: core.File,
        dialect: typing.Optional[Dialects] = OMIT,
        tone: typing.Optional[Tones] = OMIT,
        style_guide: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Start a style and brand suggestion run. Returns a workflow ID for each file.

        Parameters
        ----------
        file_upload : core.File
            See core.File for more documentation

        dialect : typing.Optional[Dialects]
            The intended dialect of the text to edit.

        tone : typing.Optional[Tones]
            The intended tone of the text to edit.

        style_guide : typing.Optional[str]
            The style guide to use for the text to edit. Can be a style guide ID or the name of a generic style guide, e.g. 'ap', 'chicago', or 'microsoft'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx import Asyncacrolinx

        client = Asyncacrolinx(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.style_suggestions.create_style_suggestion()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_style_suggestion(
            file_upload=file_upload,
            dialect=dialect,
            tone=tone,
            style_guide=style_guide,
            request_options=request_options,
        )
        return _response.data

    async def get_style_suggestion(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StyleSuggestionsGetStyleSuggestionResponse:
        """
        Get the results of a suggestion run.

        Parameters
        ----------
        workflow_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StyleSuggestionsGetStyleSuggestionResponse
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx import Asyncacrolinx

        client = Asyncacrolinx(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.style_suggestions.get_style_suggestion(
                workflow_id="workflow_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_style_suggestion(workflow_id, request_options=request_options)
        return _response.data
