# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.suggestion_response import SuggestionResponse
from ...types.workflow_status_response import WorkflowStatusResponse

StyleSuggestionsGetStyleSuggestionResponse = typing.Union[SuggestionResponse, WorkflowStatusResponse]
