# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.style_check_response import StyleCheckResponse
from ...types.workflow_status_response import WorkflowStatusResponse

StyleChecksGetStyleCheckResponse = typing.Union[StyleCheckResponse, WorkflowStatusResponse]
