# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.rewrite_response import RewriteResponse
from ...types.workflow_status_response import WorkflowStatusResponse

StyleRewritesGetStyleRewriteResponse = typing.Union[RewriteResponse, WorkflowStatusResponse]
