# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.dialects import Dialects
from ..types.tones import Tones
from ..types.workflow_response import WorkflowResponse
from .raw_client import AsyncRawStyleChecksClient, RawStyleChecksClient
from .types.style_checks_get_style_check_response import StyleChecksGetStyleCheckResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class StyleChecksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStyleChecksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStyleChecksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStyleChecksClient
        """
        return self._raw_client

    def create_style_check(
        self,
        *,
        file_upload: core.File,
        dialect: typing.Optional[Dialects] = OMIT,
        tone: typing.Optional[Tones] = OMIT,
        style_guide: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Start a style and brand check run. Returns a workflow ID for each file.

        Parameters
        ----------
        file_upload : core.File
            See core.File for more documentation

        dialect : typing.Optional[Dialects]
            The intended dialect of the text to edit.

        tone : typing.Optional[Tones]
            The intended tone of the text to edit.

        style_guide : typing.Optional[str]
            The style guide to use for the text to edit. Can be a style guide ID or the name of a generic style guide, e.g. 'ap', 'chicago', or 'microsoft'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Successful Response

        Examples
        --------
        from acrolinx import acrolinx

        client = acrolinx(
            token="YOUR_TOKEN",
        )
        client.style_checks.create_style_check()
        """
        _response = self._raw_client.create_style_check(
            file_upload=file_upload,
            dialect=dialect,
            tone=tone,
            style_guide=style_guide,
            request_options=request_options,
        )
        return _response.data

    def get_style_check(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StyleChecksGetStyleCheckResponse:
        """
        get the results of a style and brand check run.

        Parameters
        ----------
        workflow_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StyleChecksGetStyleCheckResponse
            Successful Response

        Examples
        --------
        from acrolinx import acrolinx

        client = acrolinx(
            token="YOUR_TOKEN",
        )
        client.style_checks.get_style_check(
            workflow_id="workflow_id",
        )
        """
        _response = self._raw_client.get_style_check(workflow_id, request_options=request_options)
        return _response.data


class AsyncStyleChecksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStyleChecksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStyleChecksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStyleChecksClient
        """
        return self._raw_client

    async def create_style_check(
        self,
        *,
        file_upload: core.File,
        dialect: typing.Optional[Dialects] = OMIT,
        tone: typing.Optional[Tones] = OMIT,
        style_guide: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WorkflowResponse:
        """
        Start a style and brand check run. Returns a workflow ID for each file.

        Parameters
        ----------
        file_upload : core.File
            See core.File for more documentation

        dialect : typing.Optional[Dialects]
            The intended dialect of the text to edit.

        tone : typing.Optional[Tones]
            The intended tone of the text to edit.

        style_guide : typing.Optional[str]
            The style guide to use for the text to edit. Can be a style guide ID or the name of a generic style guide, e.g. 'ap', 'chicago', or 'microsoft'.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WorkflowResponse
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx import Asyncacrolinx

        client = Asyncacrolinx(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.style_checks.create_style_check()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_style_check(
            file_upload=file_upload,
            dialect=dialect,
            tone=tone,
            style_guide=style_guide,
            request_options=request_options,
        )
        return _response.data

    async def get_style_check(
        self, workflow_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> StyleChecksGetStyleCheckResponse:
        """
        get the results of a style and brand check run.

        Parameters
        ----------
        workflow_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StyleChecksGetStyleCheckResponse
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx import Asyncacrolinx

        client = Asyncacrolinx(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.style_checks.get_style_check(
                workflow_id="workflow_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_style_check(workflow_id, request_options=request_options)
        return _response.data
