# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.suggestion_response import SuggestionResponse
from .raw_client import AsyncRawStyleSuggestionsClient, RawStyleSuggestionsClient


class StyleSuggestionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStyleSuggestionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStyleSuggestionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStyleSuggestionsClient
        """
        return self._raw_client

    def create_style_suggestion(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import Starter
        client = Starter(base_url="https://yourhost.com/path/to/api", )
        client.style_suggestions.create_style_suggestion(document_id='document_id', )
        """
        _response = self._raw_client.create_style_suggestion(document_id=document_id, request_options=request_options)
        return _response.data

    def get_style_suggestion(
        self, workflow_id: str, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuggestionResponse:
        """
        Parameters
        ----------
        workflow_id : str

        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuggestionResponse
            Successful Response

        Examples
        --------
        from acrolinx576596 import Starter
        client = Starter(base_url="https://yourhost.com/path/to/api", )
        client.style_suggestions.get_style_suggestion(workflow_id='workflow_id', document_id='document_id', )
        """
        _response = self._raw_client.get_style_suggestion(
            workflow_id, document_id=document_id, request_options=request_options
        )
        return _response.data


class AsyncStyleSuggestionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStyleSuggestionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStyleSuggestionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStyleSuggestionsClient
        """
        return self._raw_client

    async def create_style_suggestion(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import AsyncStarter
        import asyncio
        client = AsyncStarter(base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.style_suggestions.create_style_suggestion(document_id='document_id', )
        asyncio.run(main())
        """
        _response = await self._raw_client.create_style_suggestion(
            document_id=document_id, request_options=request_options
        )
        return _response.data

    async def get_style_suggestion(
        self, workflow_id: str, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> SuggestionResponse:
        """
        Parameters
        ----------
        workflow_id : str

        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SuggestionResponse
            Successful Response

        Examples
        --------
        from acrolinx576596 import AsyncStarter
        import asyncio
        client = AsyncStarter(base_url="https://yourhost.com/path/to/api", )
        async def main() -> None:
            await client.style_suggestions.get_style_suggestion(workflow_id='workflow_id', document_id='document_id', )
        asyncio.run(main())
        """
        _response = await self._raw_client.get_style_suggestion(
            workflow_id, document_id=document_id, request_options=request_options
        )
        return _response.data
