# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawStyleGuidesClient, RawStyleGuidesClient


class StyleGuidesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStyleGuidesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStyleGuidesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStyleGuidesClient
        """
        return self._raw_client

    def get_style_guides(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import acrolinx

        client = acrolinx(
            base_url="https://yourhost.com/path/to/api",
        )
        client.style_guides.get_style_guides()
        """
        _response = self._raw_client.get_style_guides(request_options=request_options)
        return _response.data

    def create_style_guide(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import acrolinx

        client = acrolinx(
            base_url="https://yourhost.com/path/to/api",
        )
        client.style_guides.create_style_guide()
        """
        _response = self._raw_client.create_style_guide(request_options=request_options)
        return _response.data

    def get_style_guide(
        self, style_guide_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        style_guide_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import acrolinx

        client = acrolinx(
            base_url="https://yourhost.com/path/to/api",
        )
        client.style_guides.get_style_guide(
            style_guide_id="style_guide_id",
        )
        """
        _response = self._raw_client.get_style_guide(style_guide_id, request_options=request_options)
        return _response.data

    def update_style_guide(
        self, style_guide_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        style_guide_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import acrolinx

        client = acrolinx(
            base_url="https://yourhost.com/path/to/api",
        )
        client.style_guides.update_style_guide(
            style_guide_id="style_guide_id",
        )
        """
        _response = self._raw_client.update_style_guide(style_guide_id, request_options=request_options)
        return _response.data

    def delete_style_guide(
        self, style_guide_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        style_guide_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx576596 import acrolinx

        client = acrolinx(
            base_url="https://yourhost.com/path/to/api",
        )
        client.style_guides.delete_style_guide(
            style_guide_id="style_guide_id",
        )
        """
        _response = self._raw_client.delete_style_guide(style_guide_id, request_options=request_options)
        return _response.data


class AsyncStyleGuidesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStyleGuidesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStyleGuidesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStyleGuidesClient
        """
        return self._raw_client

    async def get_style_guides(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx576596 import Asyncacrolinx

        client = Asyncacrolinx(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.style_guides.get_style_guides()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_style_guides(request_options=request_options)
        return _response.data

    async def create_style_guide(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx576596 import Asyncacrolinx

        client = Asyncacrolinx(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.style_guides.create_style_guide()


        asyncio.run(main())
        """
        _response = await self._raw_client.create_style_guide(request_options=request_options)
        return _response.data

    async def get_style_guide(
        self, style_guide_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        style_guide_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx576596 import Asyncacrolinx

        client = Asyncacrolinx(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.style_guides.get_style_guide(
                style_guide_id="style_guide_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_style_guide(style_guide_id, request_options=request_options)
        return _response.data

    async def update_style_guide(
        self, style_guide_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        style_guide_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx576596 import Asyncacrolinx

        client = Asyncacrolinx(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.style_guides.update_style_guide(
                style_guide_id="style_guide_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_style_guide(style_guide_id, request_options=request_options)
        return _response.data

    async def delete_style_guide(
        self, style_guide_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        style_guide_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx576596 import Asyncacrolinx

        client = Asyncacrolinx(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.style_guides.delete_style_guide(
                style_guide_id="style_guide_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_style_guide(style_guide_id, request_options=request_options)
        return _response.data
