# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.rewrite_response import RewriteResponse
from .raw_client import AsyncRawStyleRewritesClient, RawStyleRewritesClient


class StyleRewritesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawStyleRewritesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawStyleRewritesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawStyleRewritesClient
        """
        return self._raw_client

    def create_style_rewrite(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        from acrolinx import acrolinx

        client = acrolinx(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.style_rewrites.create_style_rewrite(
            document_id="document_id",
        )
        """
        _response = self._raw_client.create_style_rewrite(document_id=document_id, request_options=request_options)
        return _response.data

    def get_style_rewrite(
        self, workflow_id: str, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RewriteResponse:
        """
        Parameters
        ----------
        workflow_id : str

        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RewriteResponse
            Successful Response

        Examples
        --------
        from acrolinx import acrolinx

        client = acrolinx(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )
        client.style_rewrites.get_style_rewrite(
            workflow_id="workflow_id",
            document_id="document_id",
        )
        """
        _response = self._raw_client.get_style_rewrite(
            workflow_id, document_id=document_id, request_options=request_options
        )
        return _response.data


class AsyncStyleRewritesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawStyleRewritesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawStyleRewritesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawStyleRewritesClient
        """
        return self._raw_client

    async def create_style_rewrite(
        self, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Parameters
        ----------
        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx import Asyncacrolinx

        client = Asyncacrolinx(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.style_rewrites.create_style_rewrite(
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_style_rewrite(
            document_id=document_id, request_options=request_options
        )
        return _response.data

    async def get_style_rewrite(
        self, workflow_id: str, *, document_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> RewriteResponse:
        """
        Parameters
        ----------
        workflow_id : str

        document_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RewriteResponse
            Successful Response

        Examples
        --------
        import asyncio

        from acrolinx import Asyncacrolinx

        client = Asyncacrolinx(
            api_key="YOUR_API_KEY",
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.style_rewrites.get_style_rewrite(
                workflow_id="workflow_id",
                document_id="document_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_style_rewrite(
            workflow_id, document_id=document_id, request_options=request_options
        )
        return _response.data
