# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ClarityScore(UniversalBaseModel):
    score: float
    word_count: int
    sentence_count: int
    average_sentence_length: float
    flesch_reading_ease: float
    flesch_kincaid_grade: float
    lexical_diversity: float
    vocabulary_complexity: float
    sentence_complexity: float

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
