# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sentence_structure_category import SentenceStructureCategory


class SentenceStructureChange(UniversalBaseModel):
    original: str = pydantic.Field()
    """
    The original text
    """

    modified: str = pydantic.Field()
    """
    The modified text
    """

    change_start_char_idx: int = pydantic.Field()
    """
    The start index of the change
    """

    change_type: typing.Optional[typing.Literal["sentence_structure"]] = None
    category: SentenceStructureCategory

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
