# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .dialects import Dialects
from .tones import Tones


class StyleRequestBody(UniversalBaseModel):
    file_upload: str = pydantic.Field()
    """
    The file to process.
    """

    dialect: typing.Optional[Dialects] = pydantic.Field(default=None)
    """
    The intended dialect of the text to edit.
    """

    tone: typing.Optional[Tones] = pydantic.Field(default=None)
    """
    The intended tone of the text to edit.
    """

    style_guide: typing.Optional[str] = pydantic.Field(default=None)
    """
    The style guide to use for the text to edit. Can be a style guide ID or the name of a generic style guide, e.g. 'ap', 'chicago', or 'microsoft'.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
